### ISSUE TITLE
1.1.3节 矩阵分解中代码有误

### ISSUE THREAD

**Issue by aloneCR** [datawhalechina/fun-rec#10]
以下代码完成了对self.mu的初始化
```python
cnt = 0  # 统计总的打分数，初始化mu用
for user, items in self.rating_data.items():
    self.P[user] = [random.random() / math.sqrt(self.F)
                    for x in range(0, self.F)]
    self.bu[user] = 0
    cnt += len(items)
    for item, rating in items.items():
        # insert self.mu += rating
        if item not in self.Q:
            self.Q[item] = [random.random() / math.sqrt(self.F)
                            for x in range(0, self.F)]
            self.bi[item] = 0
self.mu /= cnt
```
此时的self.mu为0，那么执行`self.mu /= cnt`后的结果仍然是0，所以应该在第8行加入`self.mu += rating`，把self.mu变成分数之和。

**Comment by jiangshu-cn** [comment]
大佬，有没有看特征工程那部分代码，怎么只有对召回的数据构建标签了，那label不是都为0了吗，这块代码我看了几遍了

**Comment by RuyiLuo** [comment]
我有空在看一下哈，因为那边过去好久了，得重新看得花点时间，其实我都忘记了你现在说的这些东西了，晚一点给你答复

**Comment by RuyiLuo** [comment]
@jiangshu-cn 在给数据打标签的那一部分就是包括了label为0和为1的情况呀，为什么是只有label为0的呢？你那边的结果是发现label都是0么？那可能是召回部分效果不好导致的，所以打标签的时候没有1. 不知道我又没有理解到你的意思。

**Comment by aloneCR** [comment]
> 大佬，有没有看特征工程那部分代码，怎么只有对召回的数据构建标签了，那label不是都为0了吗，后面怎么训练呢，这块代码我看了几遍了

我还没看到那里去，我也是刚学这个。你有推荐系统学习交流的群吗？

**Comment by aloneCR** [comment]
> 我有空在看一下哈，因为那边过去好久了，得重新看得花点时间，其实我都忘记了你现在说的这些东西了，晚一点给你答复

好的，大佬辛苦了。

**Comment by jiangshu-cn** [comment]
@aloneCR  哦哦，没有交流群哦

**Comment by RuyiLuo** [comment]
刚才新建了一个交流群，一会我放到readme里面，欢迎大家来讨论呀

**Comment by RuyiLuo** [comment]
> 以下代码完成了对self.mu的初始化
> 
> ```python
> cnt = 0  # 统计总的打分数，初始化mu用
> for user, items in self.rating_data.items():
>     self.P[user] = [random.random() / math.sqrt(self.F)
>                     for x in range(0, self.F)]
>     self.bu[user] = 0
>     cnt += len(items)
>     for item, rating in items.items():
>         # insert self.mu += rating
>         if item not in self.Q:
>             self.Q[item] = [random.random() / math.sqrt(self.F)
>                             for x in range(0, self.F)]
>             self.bi[item] = 0
> self.mu /= cnt
> ```
> 
> 此时的self.mu为0，那么执行`self.mu /= cnt`后的结果仍然是0，所以应该在第8行加入`self.mu += rating`，把self.mu变成分数之和。

代码已经修改啦！
