### ISSUE TITLE
ItemCF 编程实现的错误

### ISSUE THREAD

**Issue by QingJun3** [datawhalechina/fun-rec#102]
复制了 ItemCF 的代码，运行出现了以下错误：
![屏幕截图 2024-02-26 102257](https://github.com/datawhalechina/fun-rec/assets/66292439/e4b7d449-13a6-4f3b-8aca-acc5cc357e54)

看了代码发现是 target_user 有问题，这里 Alice 前后有空格，导致读不到正常的 user 
![屏幕截图 2024-02-26 102403](https://github.com/datawhalechina/fun-rec/assets/66292439/bcf84f2d-cf30-4396-9ef6-fb34354ace0e)

**Comment by ruyiluo** [comment]
应该是markdown复制的时候出的问题，问题已修复，感谢反馈
