### ISSUE TITLE
Swing那一节的代码的txt文件在哪，没有找到

### ISSUE THREAD

**Issue by crow-1412** [datawhalechina/fun-rec#106]
![image](https://github.com/datawhalechina/fun-rec/assets/141846839/bdf1ecea-4310-4c6e-8e71-e41cf716e449)

**Comment by storyandwine** [comment]
朋友您好，感谢关注Fun Rec的工作，这个txt文件其实可以根据您自己的数据集来设置，整个算法的输入其实是一个pandas dataframe的结构，有三列分别为userid,itemid,rate。
为了方便学习也提供个示例数据给您
[ratings_final.txt](https://github.com/datawhalechina/fun-rec/files/15126826/ratings_final.txt)

**Comment by ruyiluo** [comment]
nice~

**Comment by crow-1412** [comment]
好的谢谢
