### ISSUE TITLE
可以上传pdf文件吗？

### ISSUE THREAD

**Issue by hothxd** [datawhalechina/fun-rec#11]
md文件中较多图片无法加载，一些公式并没有如预想的显示，是否可以上传pdf版本？非常感谢！

**Comment by RuyiLuo** [comment]
pdf目前还没有，最近有时间我检查一下内容显示的问题哈

**Comment by ZixuanMLAlgo** [comment]
> hi，图片在原文件中还是不能很好显示。只能看文字理解很吃力。
> 
> pdf目前还没有，最近有时间我检查一下内容显示的问题哈

**Comment by ZixuanMLAlgo** [comment]
> 
> 
> pdf目前还没有，最近有时间我检查一下内容显示的问题哈

hi，图片在原文件中还是不能很好显示。只能看文字理解很吃力。

**Comment by RuyiLuo** [comment]
你好，我这边刚重新下载了看了一下图片的话主要是协同过滤那一节的图片挂了，你可以先参考这个http://datawhale.club/t/topic/41，这几天我会把挂了的图片补上去，还有啥问题欢迎加交流群一起交流
