### ISSUE TITLE
求修正一下格式

### ISSUE THREAD

**Issue by 2336089258** [datawhalechina/fun-rec#12]
作者大大，您好！项目中很多地方的公式都已经显示不出来了，求修正一下，谢谢！

**Comment by RuyiLuo** [comment]
最近太忙了，等忙完这一阵子，到时候全面检查一下呀

**Comment by ZixuanMLAlgo** [comment]
下个可以mathjax的插件就可以看到公式了

> 
> 
> 作者大大，您好！项目中很多地方的公式都已经显示不出来了，求修正一下，谢谢！

**Comment by RuyiLuo** [comment]
建议使用typora看md文档，公式如果不是图片的话，不应该显示不出来 @2336089258

**Comment by RuyiLuo** [comment]
图片挂了主要在基础部分，大家可以参考之前组队学习的论坛内容（http://datawhale.club/c/team-learning/RecommendationSystem/11），上面的图片没有挂掉
