### ISSUE TITLE
部分修正版本and粗看有一些图是可用的

### ISSUE THREAD

**Issue by YuGuilliman** [datawhalechina/fun-rec#122]
这repo估计没人修了，大伙有需要的可以看下面这个，应该是对上的（不是本人的哈，别找我）
https://github.com/Hello-MLClub/Fun-Rec/tree/main

**Comment by YuGuilliman** [comment]
md，发现有用的部分就是本地markdown打开后有用的部分。治标不治本

**Comment by xuanyuanbao** [comment]
哈哈哈哈哈，你发的就找你
