### ISSUE TITLE
求上传pdf文件，不知道什么原因，里面的公式和图片都看不了

### ISSUE THREAD

**Issue by findmebynameLMH** [datawhalechina/fun-rec#13]
如题，感谢！！

**Comment by RuyiLuo** [comment]
你好，我这边刚重新下载了看了一下图片的话主要是协同过滤那一节的图片挂了，你可以先参考这个http://datawhale.club/t/topic/41，这几天我会把挂了的图片补上去，还有啥问题欢迎加交流群一起交流
