### ISSUE TITLE
1.3.1 AFM.md 的2.3里损失函数错了

### ISSUE THREAD

**Issue by wsora** [datawhalechina/fun-rec#18]
$$ L = \sum_{x\in T} (\hat{y}_{afm}(x) - y(x))^2 + \lambda ||x||^2 $$，后面那个不是对x正则，是W。应该是 $$ L = \sum_{x\in T} (\hat{y}_{afm}(x) - y(x))^2 + \lambda ||W||^2 $$

**Comment by RuyiLuo** [comment]
好的，我看一下。
