### ISSUE TITLE
公式显示是源码的形式

### ISSUE THREAD

**Issue by SSshuishui** [datawhalechina/fun-rec#19]
请问怎么才能看到md文件中源码编译后的公式？有很多都显示不出来

**Comment by RuyiLuo** [comment]
把内容拉到本地，使用typora查看md文档应该没问题，不建议直接在github上面看

**Comment by ruyiluo** [comment]
不要直接在github上看，下载下来用typora看 ry Luo ***@***.*** 签名由 网易邮箱大师 定制 在2022年04月06日 00:01，seetimee 写道：

**Comment by ruyiluo** [comment]
好的，明天我加一下，多谢提醒 ry Luo ***@***.*** 签名由 网易邮箱大师 定制 在2022年04月06日 00:22，seetimee 写道： 已经弄好了，我的意思是建议在首页readme加一句：请下载typora食用，否则公式看不了，大佬辛苦。。。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>
