### ISSUE TITLE
训练代码的输入有问题？

### ISSUE THREAD

**Issue by JoshonSmith** [datawhalechina/fun-rec#21]
# 将输入数据转化成字典的形式输入
    train_model_input = {name: data[name] for name in dense_features + sparse_features}
    # 模型训练
    history.fit(train_model_input, train_data['label'].values,
            batch_size=64, epochs=5, validation_split=0.2, )  

这里的 **data** 应该是处理好的 **train_data**吧？

**Comment by RuyiLuo** [comment]
你这个代码具体是哪一个文件呢？
