### ISSUE TITLE
文档里的图片链接失效

### ISSUE THREAD

**Issue by 1990q828j** [datawhalechina/fun-rec#26]
例如1.1.2里就有部分图片链接失效了，请及时更新一哈

**Comment by RuyiLuo** [comment]
不建议直接在github上直接看文档，我这边直接在github上直接看文档也有很多图片显示不了，但是下载到本地之后图片基本都没有问题，你说的1.1.2中的图片我这边看了都没有问题。

推荐使用typora查看md文档，我这边使用typora看是没有问题的

**Comment by RuyiLuo** [comment]
![image](https://user-images.githubusercontent.com/43609390/142955410-72fe7423-b7bb-47e8-a57c-187e9403f0d3.png)

**Comment by 1990q828j** [comment]
之前是在Typora打开有问题，在浏览器里也打不开链接。还好，现在解决了👍
