### ISSUE TITLE
[Docs] Links for some chapters in the README are wrong

### ISSUE THREAD

**Issue by Hilbert-Yaa** [datawhalechina/fun-rec#31]
README文档中章节1.1和1.2的分章节链接指向有误/失效
![image](https://user-images.githubusercontent.com/55627385/145905454-e5c6ee3c-6407-4dd9-90a0-5ad71a95774e.png)

**Comment by Hilbert-Yaa** [comment]
哈咯，我修复了一下links，请审阅 #32

**Comment by ruyiluo** [comment]
OK.
