### ISSUE TITLE
关于UserCF的公式

### ISSUE THREAD

**Issue by ewayuan** [datawhalechina/fun-rec#45]
![image](https://user-images.githubusercontent.com/28846772/153457904-2366c61d-17c8-45c7-bc54-8645a91835dd.png)
UserCF中的这个公式分母是不是应该是S_{i,k}啊，j应该是物品？

**Comment by glMa7** [comment]
对的，我也觉得是

**Comment by ruyiluo** [comment]
分母部分的确写错了，应该是$S_{i,k}$。这里的$S_{i,k}$表示的是用户i和用户k之间的相似度。原文中已经修改啦！
