### ISSUE TITLE
图片丢失问题

### ISSUE THREAD

**Issue by turkeymz** [datawhalechina/fun-rec#64]
你好，我在阅读学习https://github.com/datawhalechina/fun-rec/blob/master/docs/%E7%AC%AC%E4%B8%80%E7%AB%A0%20%E6%8E%A8%E8%8D%90%E7%B3%BB%E7%BB%9F%E5%9F%BA%E7%A1%80/1.1%20%E5%9F%BA%E7%A1%80%E6%8E%A8%E8%8D%90%E7%AE%97%E6%B3%95/1.1.2%20%E5%8D%8F%E5%90%8C%E8%BF%87%E6%BB%A4.md
发现有一些图片丢失问题。请问方便重新上传吗

**Comment by ruyiluo** [comment]
好的，我检查一下（github直接查看内容，很多图片都显示不出来，建议下载下来用typora看）
