### ISSUE TITLE
多路召回.ipynb的youtubeDNN部分

### ISSUE THREAD

**Issue by GrangerZyj** [datawhalechina/fun-rec#65]
> model = YoutubeDNN(user_feature_columns, item_feature_columns, num_sampled=5, user_dnn_hidden_units=(64, embedding_dim))

出现bug [Could not build a TypeSpec for <KerasTensor: shape=(None, 16) dtype=float32 (created by layer 'tf.compat.v1.squeeze_3')> with type KerasTensor]()

是keras和TensorFlow版本问题吗，我都是2.6.0版本

**Comment by ruyiluo** [comment]
可能版本太高了，我记得当初使用的tf版本是tf2.0或者tf1.14

**Comment by GrangerZyj** [comment]
我看deepmatch是支持2.0+的，是因为deepmatch的版本问题吗 可以给一下requirement.txt吗 QAQ

**Comment by GrangerZyj** [comment]
> 可能版本太高了，我记得当初使用的tf版本是tf2.0或者tf1.14


我看deepmatch是支持2.0+的，是因为deepmatch的版本问题吗 可以给一下requirement.txt吗 QAQ

**Comment by ruyiluo** [comment]
换成tf1.14大概率没啥问题，这个印象比较深刻，主要就是tf的版本问题，其他的都没问题的

**Comment by ruyiluo** [comment]
这个环境太早了，我准备已经没有那个环境了

**Comment by GrangerZyj** [comment]
qaq 谢谢大佬了
