### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by joyenjoye** [datawhalechina/fun-rec#79]
https://github.com/datawhalechina/fun-rec/blob/master/docs/ch01/ch1.2.md

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/29893343/172399365-91b4bde8-3a6a-470a-9fc7-5db3bbca4228.png">

是应该是分布式框架？

**Comment by joyenjoye** [comment]
https://github.com/datawhalechina/fun-rec/blob/master/docs/ch01/ch1.3.md

![image](https://user-images.githubusercontent.com/29893343/173376387-eeda27bf-915f-4f2c-b0ab-905320df36d1.png)

Saprk -> Spark

**Comment by ruyiluo** [comment]
OK，已经修正
