### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by 591343** [datawhalechina/fun-rec#80]
deepctr 和tensorflow的版本是多少

**Comment by ruyiluo** [comment]
你指的是哪里代码的deepctr的版本?具体是哪个文件呢？

**Comment by ruyiluo** [comment]
codes下厨除了base_model文件下的所有代码使用tf 1.14.0 gpu 版本外（以及新闻推荐竞赛相关的代码），其他的代码都使用tf2.2.x gpu版就行
