### ISSUE TITLE
新闻推荐数据集

### ISSUE THREAD

**Issue by shenzheyu** [datawhalechina/fun-rec#83]
请问新闻推荐数据集在哪里公开的，可以在论文中引用吗？

**Comment by ruyiluo** [comment]
这个数据是科大讯飞的一个比赛数据集，你去看一下他们官网上对应的是那一个竞赛吧，最好咨询一下他们工作人员，我们不确定能不能在论文中引用

**Comment by shenzheyu** [comment]
谢谢
