### ISSUE TITLE
4.1 ML与DL基础

### ISSUE THREAD

**Issue by Heitao5200** [datawhalechina/fun-rec#84]
`bagging与boosting分别从什么角度降低过拟合？
bagging降低方差，boosting降低方差` 
bagging降低variance。boosting降低bias来提升预测精度。

**Comment by ruyiluo** [comment]
有一种经验说法认为boosting对过拟合有一定的稳健性，不太容易过拟合，泛化能力不错。这种稳健性不是源于boosting(boosting本身是会加剧overfit的），而是源于弱模型合成（加权平均）过程中的“投票”效果，而且，我们总是可以使用交叉验证，及时停止boosting，避免合成过多的模型

参考链接：https://zhuanlan.zhihu.com/p/517900957
