### ISSUE TITLE
不清楚

### ISSUE THREAD

**Issue by T-Y404** [datawhalechina/fun-rec#85]
![image](https://user-images.githubusercontent.com/57243868/188303649-15fa87b6-eca8-4423-b214-b90fb8f03e83.png)
这个s2是指什么，是Swing吗，
https://datawhalechina.github.io/fun-rec/#/ch02/ch2.1/ch2.1.1/Swing

**Comment by storyandwine** [comment]
s2指的是，基于i和j的聚类类别算出来的相似度。
<img width="937" alt="image" src="https://user-images.githubusercontent.com/27343352/221466944-a9f292d5-65ef-482a-9107-49dbbd47a0ff.png">
其中L(i),L(j)为i,j的聚类类别
总的相似度定义为两种层级相似度的结合
