### ISSUE TITLE
大佬你好，请问一下文本推荐系统的YouTubeDNN模型召回那里，gen_data_set里面的test_set的label为什么是0啊

### ISSUE THREAD

**Issue by 2628667209** [datawhalechina/fun-rec#94]
大佬你好，请问一下文本推荐系统的YouTubeDNN模型召回那里，gen_data_set里面的test_set的label为什么是0啊

**Comment by ruyiluo** [comment]
1. youtubednn模型对应的样本是不需要显示的构造负样本的，所以样本中都是用户点击的，也就是整样本
2. 你看到代码中往train_data中塞负样本，是因为该函数也被用来构造双塔模型的样本，对于双塔模型来说，一般是显示的构造负样本
3. 最终对于youtube构造的样本来说，其函数对应的负样本参数设置的是0

有问题欢迎首页加微信聊
