### ISSUE TITLE
请问这个package是什么？

### ISSUE THREAD

**Issue by yusiwen** [datawhalechina/fun-rec#95]
在`codes/news_recsys/news_rec_server/recprocess/recall/u2i_usercf.ipynb` notebook里有这个依赖：

```python
from metric import PrintMetric
```

但是我找不到正确的metric包，我用`pip install metric`安装的metric包里没有`PrintMetric`。

请问这个包在哪里下载？

谢谢啦

**Comment by ruyiluo** [comment]
不好意思，这个好像是自己写的包，貌似忘记传了，我们再找找

有问题欢迎首页加微信聊

**Comment by Lyons-T** [comment]
import numpy as np
import pandas as pd


def PrintMetric(actual, predicted, topk=10):

    print(f"MAP@{topk}: ", MapK(actual, predicted, topk))

    print(f"Recall@{topk}: ", Recall(actual, predicted, topk))

    print(f"Precision@{topk}: ", Precision(actual, predicted, topk))

    print(f"F1@{topk}: ", F1(actual, predicted, topk))


# Source: https://github.com/benhamner/Metrics/blob/master/Python/ml_metrics/average_precision.py
def apk(actual, predicted, k=10):
    if len(predicted) > k:
        predicted = predicted[:k]

    score = 0.0
    num_hits = 0.0

    for i, p in enumerate(predicted):
        if p in actual and p not in predicted[:i]:
            num_hits += 1.0
            score += num_hits / (i+1.0)

    if not actual:
        return 0.0

    return score / min(len(actual), k)


def MapK(actual, predicted, k=12):
    return np.mean([apk(a, p, k) for a, p in zip(actual, predicted) if a])


def recall(true, predict, n=10):
    if len(predict) > n:
        predict = predict[:n]

    num_hits = 0.0
    for i, p in enumerate(predict):
        if p in true and p not in predict[:i]:
            num_hits += 1.0

    if not true:
        return 0.0

    return num_hits / min(len(true), n)


def Recall(actual, predicted, k=12):
    return np.mean([recall(a, p, k) for a, p in zip(actual, predicted) if a])


def precision(true, predict, n=10):
    if len(predict) > n:
        predict = predict[:n]

    num_hits = 0.0
    for i, p in enumerate(predict):
        if p in true and p not in predict[:i]:
            num_hits += 1.0

    if not true:
        return 0.0

    return num_hits / n


def Precision(actual, predicted, k=12):
    return np.mean([precision(a, p, k) for a, p in zip(actual, predicted) if a])


def F1(actual, predicted, k=12):
    def f1(p, r):
        if p == 0 and r == 0:
            return .0

        score = 2 * p * r
        score /= (p + r)
        return score

    return np.mean([f1(precision(a, p, k), recall(a, p, k)) for a, p in zip(actual, predicted) if a])


def NDCG():
    pass

**Comment by Lyons-T** [comment]
`import numpy as np
import pandas as pd


def PrintMetric(actual, predicted, topk=10):

    print(f"MAP@{topk}: ", MapK(actual, predicted, topk))

    print(f"Recall@{topk}: ", Recall(actual, predicted, topk))

    print(f"Precision@{topk}: ", Precision(actual, predicted, topk))

    print(f"F1@{topk}: ", F1(actual, predicted, topk))


# Source: https://github.com/benhamner/Metrics/blob/master/Python/ml_metrics/average_precision.py
def apk(actual, predicted, k=10):
    if len(predicted) > k:
        predicted = predicted[:k]

    score = 0.0
    num_hits = 0.0

    for i, p in enumerate(predicted):
        if p in actual and p not in predicted[:i]:
            num_hits += 1.0
            score += num_hits / (i+1.0)

    if not actual:
        return 0.0

    return score / min(len(actual), k)


def MapK(actual, predicted, k=12):
    return np.mean([apk(a, p, k) for a, p in zip(actual, predicted) if a])


def recall(true, predict, n=10):
    if len(predict) > n:
        predict = predict[:n]

    num_hits = 0.0
    for i, p in enumerate(predict):
        if p in true and p not in predict[:i]:
            num_hits += 1.0

    if not true:
        return 0.0

    return num_hits / min(len(true), n)


def Recall(actual, predicted, k=12):
    return np.mean([recall(a, p, k) for a, p in zip(actual, predicted) if a])


def precision(true, predict, n=10):
    if len(predict) > n:
        predict = predict[:n]

    num_hits = 0.0
    for i, p in enumerate(predict):
        if p in true and p not in predict[:i]:
            num_hits += 1.0

    if not true:
        return 0.0

    return num_hits / n


def Precision(actual, predicted, k=12):
    return np.mean([precision(a, p, k) for a, p in zip(actual, predicted) if a])


def F1(actual, predicted, k=12):
    def f1(p, r):
        if p == 0 and r == 0:
            return .0

        score = 2 * p * r
        score /= (p + r)
        return score

    return np.mean([f1(precision(a, p, k), recall(a, p, k)) for a, p in zip(actual, predicted) if a])


def NDCG():
    pass`

**Comment by Lyons-T** [comment]
`import numpy as np
import pandas as pd


def PrintMetric(actual, predicted, topk=10):

    print(f"MAP@{topk}: ", MapK(actual, predicted, topk))

    print(f"Recall@{topk}: ", Recall(actual, predicted, topk))

    print(f"Precision@{topk}: ", Precision(actual, predicted, topk))

    print(f"F1@{topk}: ", F1(actual, predicted, topk))


# Source: https://github.com/benhamner/Metrics/blob/master/Python/ml_metrics/average_precision.py
def apk(actual, predicted, k=10):
    if len(predicted) > k:
        predicted = predicted[:k]

    score = 0.0
    num_hits = 0.0

    for i, p in enumerate(predicted):
        if p in actual and p not in predicted[:i]:
            num_hits += 1.0
            score += num_hits / (i+1.0)

    if not actual:
        return 0.0

    return score / min(len(actual), k)


def MapK(actual, predicted, k=12):
    return np.mean([apk(a, p, k) for a, p in zip(actual, predicted) if a])


def recall(true, predict, n=10):
    if len(predict) > n:
        predict = predict[:n]

    num_hits = 0.0
    for i, p in enumerate(predict):
        if p in true and p not in predict[:i]:
            num_hits += 1.0

    if not true:
        return 0.0

    return num_hits / min(len(true), n)


def Recall(actual, predicted, k=12):
    return np.mean([recall(a, p, k) for a, p in zip(actual, predicted) if a])


def precision(true, predict, n=10):
    if len(predict) > n:
        predict = predict[:n]

    num_hits = 0.0
    for i, p in enumerate(predict):
        if p in true and p not in predict[:i]:
            num_hits += 1.0

    if not true:
        return 0.0

    return num_hits / n


def Precision(actual, predicted, k=12):
    return np.mean([precision(a, p, k) for a, p in zip(actual, predicted) if a])


def F1(actual, predicted, k=12):
    def f1(p, r):
        if p == 0 and r == 0:
            return .0

        score = 2 * p * r
        score /= (p + r)
        return score

    return np.mean([f1(precision(a, p, k), recall(a, p, k)) for a, p in zip(actual, predicted) if a])


def NDCG():
    pass
`
