### ISSUE TITLE
【资料自荐】fun-rec项目或许可以加入如下repo

### ISSUE THREAD

**Issue by Doragd** [datawhalechina/fun-rec#97]
同学你好，很高兴能够看到这个开源项目能够帮助大家入门推荐系统。
在此，希望自荐我的个人开源项目：https://github.com/Doragd/Algorithm-Practice-in-Industry 
询问是否能够加入到fun-rec项目中

【为什么想加入】：推荐系统是一个非常偏工业界实践的领域，除开基础知识和代码实践外，我觉得非常有用的资料是各个大厂的技术分享文章以及搜广推顶会上的文章。因此，我认为我的项目或许能够帮助fun-rec完善这一部分。
【我的项目是什么】：我的项目收集了：
* 知乎上的关于搜广推算法系列串讲/经典问题
* 各个大厂的搜广推实践分享，大概有400多篇吧（2017-2023）
* 搜广推顶会列表以及翻译：2012-2023，涵盖了sigir/www/recsys/kdd/cikm/wsdm等

希望同学可以不吝赐教我的项目：https://github.com/Doragd/Algorithm-Practice-in-Industry 
希望以一种合适的方式能够加入fun-rec中，为这个项目添砖加瓦。

此致，
Gordon Lee

**Comment by ruyiluo** [comment]
加微信聊一下，我的微信是LOOrze
