### ISSUE TITLE
Youbute dnn的一个疑问

### ISSUE THREAD

**Issue by DC-fan** [datawhalechina/fun-rec#98]
![image](https://github.com/datawhalechina/fun-rec/assets/54201996/361206f8-32dc-4afe-81bb-14966066bb3e)
这里提到可以增加item的特征, 但是我在使用时出现报错 "Now YoutubeNN only support 1 item feature like item_id", 使用的版本是deepmatch(0.3.1), deepctr(0.9.3)
另一个问题是example_age的使用, 我理解这是一个item 的特征, 那么我是不是可以将其他的特征封装到user_feature_columns里面呢

**Comment by ruyiluo** [comment]
1、youtubednn应该是不可以加item其他维度的特征了，这里写错了
2、item特征应该是无法直接使用到youtube里面的，这里的example_age，应该指的是样本的特征，可以参考下面的文章
![image](https://github.com/datawhalechina/fun-rec/assets/43609390/49bc3350-f67a-4079-ba9a-5eac5793a920)

链接：https://zhuanlan.zhihu.com/p/52504407
